name: ayoub_blog
description: A new Flutter project showing a blog in WebView.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
